//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.DanhMuc1 = new HashSet<DanhMuc>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MADM { get; set; }
        public string TENDM { get; set; }
        public Nullable<int> MADM_CHA { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<DanhMuc> DanhMuc1 { get; set; }
        public virtual DanhMuc DanhMuc2 { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
