//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public GioHang()
        {
        }

        public GioHang(int maSP, int soLuong)
        {
            MASP = maSP;
            SOLUONG = soLuong;
        }

        public int MAGH { get; set; }
        public Nullable<int> MAND { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
        public string Anh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
