//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MAKM { get; set; }
        public string TENKM { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
