//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSanPham
    {
        public PhanLoaiSanPham()
        {
            this.SanPham_PhanLoai = new HashSet<SanPham_PhanLoai>();
        }
    
        public int MAPHANLOAI { get; set; }
        public string TENPHANLOAI { get; set; }
        public string MOTA { get; set; }
        public string URL_ANH_BANNER { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> THUTU { get; set; }
    
        public virtual ICollection<SanPham_PhanLoai> SanPham_PhanLoai { get; set; }
    }
}
