//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_PhanLoai
    {
        public int MASP { get; set; }
        public int MAPHANLOAI { get; set; }
        public Nullable<int> THUTUHIENTHI { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
    
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
